# Generated by Django 4.1.6 on 2023-02-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_no', models.CharField(max_length=10)),
                ('to_no', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
